// 02_Frontend/innovatube/src/components/Security/Password/ForgotPasswordComponent.jsx
import { useForm } from "react-hook-form";
import Swal from "sweetalert2";
import { useState } from "react";
import { API_FORGOT_PASSWORD } from "../../../services/servicesApi";

const ForgotPassword = () => {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const [sent, setSent] = useState(false);

  const onSubmit = async (data) => {
    try {
      const res = await fetch(API_FORGOT_PASSWORD, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ Email: data.email }),
      });

      const msg = await res.text();
      if (res.ok) {
        setSent(true);
        Swal.fire("Éxito", msg, "success");
      } else {
        Swal.fire("Error", msg, "error");
      }
    } catch (err) {
      Swal.fire("Error", "No se pudo enviar la solicitud", "error");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="w-full max-w-md bg-white p-6 rounded shadow-md">
        <h2 className="text-xl font-bold text-center mb-4">¿Olvidaste tu contraseña?</h2>
        {sent ? (
          <p className="text-green-600 text-center">
            Revisa tu correo para restablecer la contraseña.
          </p>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)}>
            <label className="block text-sm font-medium text-gray-700">
              Correo electrónico
            </label>
            <input
              type="email"
              {...register("email", {
                required: "El correo es obligatorio",
                pattern: {
                  value: /^\S+@\S+$/i,
                  message: "Correo inválido"
                }
              })}
              className="w-full px-4 py-2 mt-2 border rounded-md"
            />
            {errors.email && (
              <p className="text-red-500 text-sm mt-1">{errors.email.message}</p>
            )}

            <button
              type="submit"
              className="w-full mt-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              Enviar enlace
            </button>
          </form>
        )}
      </div>
    </div>
  );
};

export default ForgotPassword;

// 05_Frontend_Angular/innovatube-angular/src/app/pages/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import Swal from 'sweetalert2';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

const API_FORGOT_PASSWORD = 'https://innovatube20250629202212.azurewebsites.net/api/forgot-password';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.css']
})
export class ForgotPasswordComponent {
  form: FormGroup;
  sent = false;

  constructor(private fb: FormBuilder, private http: HttpClient) {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]]
    });
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    try {
      const response = await this.http.post(API_FORGOT_PASSWORD, { Email: this.form.value.email }, { responseType: 'text' }).toPromise();

      this.sent = true;
      Swal.fire('Éxito', response || 'Correo enviado correctamente', 'success');
    } catch (error: any) {
      const msg = error?.error || 'No se pudo enviar la solicitud';
      Swal.fire('Error', msg, 'error');
    }
  }
}

<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <div class="w-full max-w-md bg-white p-6 rounded shadow-md">
    <h2 class="text-xl font-bold text-center mb-4">¿Olvidaste tu contraseña?</h2>

    <ng-container *ngIf="sent; else formBlock">
      <p class="text-green-600 text-center">
        Revisa tu correo para restablecer la contraseña.
      </p>
    </ng-container>

    <ng-template #formBlock>
      <form [formGroup]="form" (ngSubmit)="onSubmit()">
        <label class="block text-sm font-medium text-gray-700">
          Correo electrónico
        </label>
        <input
          type="email"
          formControlName="email"
          class="w-full px-4 py-2 mt-2 border rounded-md"
        />
        <p *ngIf="form.get('email')?.invalid && form.get('email')?.touched"
           class="text-red-500 text-sm mt-1">
          {{ form.get('email')?.errors?.['required'] ? 'El correo es obligatorio' : 'Correo inválido' }}
        </p>

        <button
          type="submit"
          class="w-full mt-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          Enviar enlace
        </button>
      </form>
    </ng-template>
  </div>
</div>
