// 02_Frontend/innovatube/src/components/Videos/SearchBarComponent.jsx

import { useState } from 'react';

const SearchBar = ({ onSearch }) => {
  const [query, setQuery] = useState('');

  const handleSearch = (e) => {
    e.preventDefault();
    if (query.trim()) {
      onSearch(query.trim());
    }
  };

  return (
    <form onSubmit={handleSearch} className="mb-6 flex justify-center">
      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Buscar videos de YouTube..."
        className="px-4 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500 w-full max-w-lg"
      />
      <button
        type="submit"
        className="bg-blue-600 text-white px-4 py-2 rounded-r-md hover:bg-blue-700"
      >
        Buscar
      </button>
    </form>
  );
};

export default SearchBar;

// 05_Frontend_Angular/innovatube-angular/src/app/pages/search-bar/search-bar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-search-bar',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './search-bar.component.html'
})
export class SearchBarComponent {
  query: string = '';

  @Output() search = new EventEmitter<string>();

  handleSearch(event: Event): void {
    event.preventDefault();
    const trimmed = this.query.trim();
    if (trimmed) {
      this.search.emit(trimmed);
    }
  }
}

<form (submit)="handleSearch($event)" class="mb-6 flex justify-center">
  <input
    type="text"
    [(ngModel)]="query"
    name="query"
    placeholder="Buscar videos de YouTube..."
    class="px-4 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500 w-full max-w-lg"
  />
  <button
    type="submit"
    class="bg-blue-600 text-white px-4 py-2 rounded-r-md hover:bg-blue-700"
  >
    Buscar
  </button>
</form>
