// 02_Frontend/innovatube/src/components/Videos/VideosComponent.jsx
import { useEffect, useState, useContext } from 'react';
import axios from 'axios';
import { API_ADD_FAVORITE, API_KEY } from '../../services/servicesApi';
import { AuthContext } from '../../context/AuthContext';
import SearchBar from './SearchBarComponent';
import Toast from '../ToastComponent';

const VideosComponent = () => {
  const [videos, setVideos] = useState([]);
  const [searchQuery, setSearchQuery] = useState(null);
  const [toastMessage, setToastMessage] = useState('');

  const [tokenHistory, setTokenHistory] = useState(['']);
  const [currentPage, setCurrentPage] = useState(0);
  const [nextPageToken, setNextPageToken] = useState('');

  const { getDecodedToken } = useContext(AuthContext);
  const userId = getDecodedToken()?.Id;
  

  const fetchVideos = async (query = null, token = '') => {
    try {
      const baseUrl = query
        ? `https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=12&q=${query}&pageToken=${token}&key=${API_KEY}`
        : `https://www.googleapis.com/youtube/v3/videos?part=snippet&chart=mostPopular&regionCode=MX&maxResults=12&pageToken=${token}&key=${API_KEY}`;

      const res = await axios.get(baseUrl);

      const items = query
        ? res.data.items.map((item) => ({
            id: item.id.videoId,
            snippet: item.snippet,
          }))
        : res.data.items;

      setVideos(items);
      setNextPageToken(res.data.nextPageToken || '');
    } catch (error) {
      console.error('Error al cargar videos', error);
    }
  };

  const goToPage = (index) => {
    const token = tokenHistory[index];
    fetchVideos(searchQuery, token);
    setCurrentPage(index);
  };

  const goToNext = () => {
    if (!nextPageToken) return;
    const newHistory = [...tokenHistory];
    newHistory[currentPage + 1] = nextPageToken;
    setTokenHistory(newHistory);
    fetchVideos(searchQuery, nextPageToken);
    setCurrentPage((prev) => prev + 1);
  };

  const goToPrev = () => {
    if (currentPage === 0) return;
    const token = tokenHistory[currentPage - 1];
    fetchVideos(searchQuery, token);
    setCurrentPage((prev) => prev - 1);
  };

  const handleSearch = (query) => {
    setSearchQuery(query);
    setTokenHistory(['']);
    setCurrentPage(0);
    fetchVideos(query, '');
  };

  const handleFavorite = async (video) => {
    try {
      await axios.post(`${API_ADD_FAVORITE}?userId=${userId}`, {
        IdVideo: video.id,
        Title: video.snippet.title,
        ThumbnailUrl: video.snippet.thumbnails.medium.url,
        PublishedAt: video.snippet.publishedAt,
      });
      setToastMessage('Video agregado a favoritos');
    } catch (err) {
      setToastMessage('El video ya está en favoritos');
    }
  };

  const handleShare = (videoId) => {
    const url = `https://www.youtube.com/watch?v=${videoId}`;
    if (navigator.share) {
      navigator.share({ title: 'Mira este video', url }).catch(console.log);
    } else {
      navigator.clipboard.writeText(url).then(() => {
        setToastMessage('Enlace copiado al portapapeles');
      });
    }
  };

  useEffect(() => {
    fetchVideos();
  }, []);

  return (
    <div className="p-4">
      <SearchBar onSearch={handleSearch} />

      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {videos.map((video) => (
          <div
            key={video.id}
            className="bg-white rounded-2xl shadow-md overflow-hidden transform hover:scale-105 transition duration-300 flex flex-col"
          >
            <img
              src={video.snippet.thumbnails.medium.url}
              alt={video.snippet.title}
              className="w-full h-48 object-cover"
            />
            <div className="p-4 flex flex-col justify-between h-full">
              <h3 className="text-base font-semibold mb-2 text-gray-800 line-clamp-2">
                {video.snippet.title}
              </h3>

              <div className="flex gap-3 mt-auto justify-end">
                <button
                  onClick={() => handleFavorite(video)}
                  className="text-lg p-2 rounded hover:bg-gray-200"
                  aria-label="Agregar a favoritos"
                >
                  ❤️
                </button>

                <button
                  onClick={() => handleShare(video.id)}
                  className="bg-gray-200 text-gray-700 p-2 rounded hover:bg-gray-300 flex items-center justify-center"
                  aria-label="Compartir video"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15 8a3 3 0 10-2.83-4H7a3 3 0 100 6h2.17A3 3 0 1015 8zM9 12v7a3 3 0 11-6 0v-7m12-1v7a3 3 0 11-6 0v-7"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="flex flex-wrap justify-center items-center gap-2 mt-10">
        <button
          disabled={currentPage === 0}
          onClick={goToPrev}
          className={`px-3 py-1 rounded ${
            currentPage === 0
              ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
              : 'bg-gray-300 text-gray-700 hover:bg-gray-400'
          }`}
        >
          Anterior
        </button>

        {tokenHistory.map((_, index) => (
          <button
            key={index}
            onClick={() => goToPage(index)}
            className={`px-3 py-1 rounded ${
              currentPage === index
                ? 'bg-blue-600 text-white'
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            }`}
          >
            {index + 1}
          </button>
        ))}

        <button
          disabled={!nextPageToken}
          onClick={goToNext}
          className={`px-3 py-1 rounded ${
            !nextPageToken
              ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
              : 'bg-blue-600 text-white hover:bg-blue-700'
          }`}
        >
          Siguiente
        </button>
      </div>

      {toastMessage && (
        <Toast message={toastMessage} onClose={() => setToastMessage('')} />
      )}
    </div>
  );
};

export default VideosComponent;

// 05_Frontend_Angular/innovatube-angular/src/app/pages/videos-page/videos.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { API_ENDPOINTS, YOUTUBE_API_KEY } from '../../config/api-endpoints';
import { AuthService } from '../../auth/auth.service';
import { DomSanitizer } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { NgIf, NgFor, NgClass } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SearchBarComponent } from '../search-bar/search-bar.component';

@Component({
  selector: 'app-videos',
  standalone: true,
  imports: [
    CommonModule,
    NgIf,
    NgFor,
    NgClass,
    FormsModule,
    // DatePipe,
    SearchBarComponent
  ],
  templateUrl: './videos.component.html'
})
export class VideosComponent implements OnInit {
  videos: any[] = [];
  searchQuery: string | null = null;
  toastMessage = '';
  currentPage = 0;
  nextPageToken = '';
  tokenHistory: string[] = [''];
  userId!: string;

  constructor(
    private http: HttpClient,
    private authService: AuthService,
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit(): void {
    const token = this.authService.getDecodedToken();
    this.userId = token?.Id?.toString() ?? '';
    this.fetchVideos();
  }

  fetchVideos(query: string | null = null, token: string = '') {
    const baseUrl = query
      ? `https://www.googleapis.com/youtube/v3/search`
      : `https://www.googleapis.com/youtube/v3/videos`;

    let params = new HttpParams()
      .set('part', 'snippet')
      .set('maxResults', '12')
      .set('key', YOUTUBE_API_KEY)
      .set('pageToken', token);

    if (query) {
      params = params.set('q', query).set('type', 'video');
    } else {
      params = params.set('chart', 'mostPopular').set('regionCode', 'MX');
    }

    this.http.get<any>(baseUrl, { params }).subscribe({
      next: (res) => {
        this.nextPageToken = res.nextPageToken || '';
        this.videos = query
          ? res.items.map((item: any) => ({
              id: item.id.videoId,
              snippet: item.snippet
            }))
          : res.items;
      },
      error: (err) => console.error('Error al cargar videos', err)
    });
  }

  goToPage(index: number) {
    const token = this.tokenHistory[index];
    this.fetchVideos(this.searchQuery, token);
    this.currentPage = index;
  }

  goToNext() {
    if (!this.nextPageToken) return;
    this.tokenHistory[this.currentPage + 1] = this.nextPageToken;
    this.fetchVideos(this.searchQuery, this.nextPageToken);
    this.currentPage++;
  }

  goToPrev() {
    if (this.currentPage === 0) return;
    const token = this.tokenHistory[this.currentPage - 1];
    this.fetchVideos(this.searchQuery, token);
    this.currentPage--;
  }

  handleSearch(query: string) {
    this.searchQuery = query;
    this.tokenHistory = [''];
    this.currentPage = 0;
    this.fetchVideos(query, '');
  }

  handleFavorite(video: any) {
    const body = {
      IdVideo: video.id,
      Title: video.snippet.title,
      ThumbnailUrl: video.snippet.thumbnails.medium.url,
      PublishedAt: video.snippet.publishedAt
    };

    this.http.post(`${API_ENDPOINTS.ADD_FAVORITE}?userId=${this.userId}`, body).subscribe({
      next: () => (this.toastMessage = 'Video agregado a favoritos'),
      error: () => (this.toastMessage = 'El video ya está en favoritos')
    });
  }

  handleShare(videoId: string) {
    const url = `https://www.youtube.com/watch?v=${videoId}`;
    if (navigator.share) {
      navigator.share({ title: 'Mira este video', url }).catch(console.log);
    } else {
      navigator.clipboard.writeText(url).then(() => {
        this.toastMessage = 'Enlace copiado al portapapeles';
      });
    }
  }

  closeToast() {
    this.toastMessage = '';
  }
}

<app-search-bar (search)="handleSearch($event)"></app-search-bar>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
  <div
    *ngFor="let video of videos"
    class="bg-white rounded-2xl shadow-md overflow-hidden transform hover:scale-105 transition duration-300 flex flex-col"
  >
    <img
      [src]="video.snippet.thumbnails.medium.url"
      [alt]="video.snippet.title"
      class="w-full h-48 object-cover"
    />
    <div class="p-4 flex flex-col justify-between h-full">
      <h3 class="text-base font-semibold mb-2 text-gray-800 line-clamp-2">
        {{ video.snippet.title }}
      </h3>

      <div class="flex gap-3 mt-auto justify-end">
        <button
          (click)="handleFavorite(video)"
          class="text-lg p-2 rounded hover:bg-gray-200"
          aria-label="Agregar a favoritos"
        >
          ❤️
        </button>

        <button
          (click)="handleShare(video.id)"
          class="bg-gray-200 text-gray-700 p-2 rounded hover:bg-gray-300 flex items-center justify-center"
          aria-label="Compartir video"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M15 8a3 3 0 10-2.83-4H7a3 3 0 100 6h2.17A3 3 0 1015 8zM9 12v7a3 3 0 11-6 0v-7m12-1v7a3 3 0 11-6 0v-7"
            />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Paginación -->
<div class="flex flex-wrap justify-center items-center gap-2 mt-10">
  <button
    [disabled]="currentPage === 0"
    (click)="goToPrev()"
    class="px-3 py-1 rounded"
    [ngClass]="{
      'bg-gray-200 text-gray-400 cursor-not-allowed': currentPage === 0,
      'bg-gray-300 text-gray-700 hover:bg-gray-400': currentPage > 0
    }"
  >
    Anterior
  </button>

  <button
    *ngFor="let token of tokenHistory; index as i"
    (click)="goToPage(i)"
    class="px-3 py-1 rounded"
    [ngClass]="{
      'bg-blue-600 text-white': currentPage === i,
      'bg-gray-200 text-gray-700 hover:bg-gray-300': currentPage !== i
    }"
  >
    {{ i + 1 }}
  </button>

  <button
    [disabled]="!nextPageToken"
    (click)="goToNext()"
    class="px-3 py-1 rounded"
    [ngClass]="{
      'bg-gray-200 text-gray-400 cursor-not-allowed': !nextPageToken,
      'bg-blue-600 text-white hover:bg-blue-700': nextPageToken
    }"
  >
    Siguiente
  </button>
</div>

<!-- Toast -->
<div
  *ngIf="toastMessage"
  class="fixed bottom-5 left-1/2 transform -translate-x-1/2 bg-gray-800 text-white px-4 py-2 rounded"
>
  {{ toastMessage }}
  <button (click)="closeToast()" class="ml-2 text-sm">x</button>
</div>
