// 05_Frontend_Angular/innovatube-angular/src/app/pages/toast/toast.component.ts
import { Component, Input, Output, EventEmitter, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-toast',
  templateUrl: './toast.component.html',
  standalone: true,
  styleUrls: ['./toast.component.css'] // opcional si tienes estilos aparte
})
export class ToastComponent implements OnDestroy {
  @Input() duration = 3000;
  @Output() onClose = new EventEmitter<void>();

  message: string = '';
  visible: boolean = false;
  private timer: any;

  show(message: string): void {
    this.message = message;
    this.visible = true;

    if (this.timer) {
      clearTimeout(this.timer);
    }

    this.timer = setTimeout(() => {
      this.visible = false;
      this.onClose.emit();
    }, this.duration);
  }

  ngOnDestroy(): void {
    if (this.timer) {
      clearTimeout(this.timer);
    }
  }
}

<div *ngIf="visible" class="fixed bottom-4 right-4 bg-gray-800 text-white px-4 py-2 rounded shadow-lg z-50">
  {{ message }}
</div>

// 02_Frontend/innovatube/src/components/ToastComponent.jsx
import { useEffect } from 'react';

const ToastComponent = ({ message, onClose, duration = 3000 }) => {
  useEffect(() => {
    const timer = setTimeout(onClose, duration);
    return () => clearTimeout(timer);
  }, [onClose, duration]);

  return (
    <div className="fixed bottom-6 left-1/2 transform -translate-x-1/2 bg-gray-900 text-white px-6 py-3 rounded shadow-lg z-50 select-none">
      {message}
    </div>
  );
};

export default ToastComponent;
