// 05_Frontend_Angular/innovatube-angular/src/app/pages/reset-password-page/reset-password.component.ts
// src/app/pages/reset-password/reset-password.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import Swal from 'sweetalert2';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { API_ENDPOINTS } from '../../config/api-endpoints';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [ReactiveFormsModule, HttpClientModule],
  templateUrl: './reset-password.component.html'
})
export class ResetPasswordComponent {
  form: FormGroup;
  token: string | null = null;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private http: HttpClient,
    private router: Router
  ) {
    this.token = this.route.snapshot.queryParamMap.get('token');

    this.form = this.fb.group({
      password: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]]
    }, {
      validators: this.passwordMatchValidator
    });
  }

  passwordMatchValidator(group: FormGroup) {
    const pass = group.get('password')?.value;
    const confirm = group.get('confirmPassword')?.value;
    return pass === confirm ? null : { passwordMismatch: true };
  }

  async onSubmit(): Promise<void> {
    if (!this.token || this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const payload = {
      token: this.token,
      NewPassword: this.form.get('password')?.value
    };

    try {
      const response = await this.http.post(API_ENDPOINTS.RESET_PASSWORD, payload, { responseType: 'text' }).toPromise();

      Swal.fire('Éxito', response || 'Contraseña cambiada correctamente', 'success')
        .then(() => this.router.navigate(['/']));
    } catch (error: any) {
      const msg = error?.error || 'No se pudo cambiar la contraseña';
      Swal.fire('Error', msg, 'error');
    }
  }
}

<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <div class="w-full max-w-md bg-white p-6 rounded shadow-md">
    <h2 class="text-xl font-bold text-center mb-4">Restablecer contraseña</h2>
    <form [formGroup]="form" (ngSubmit)="onSubmit()">

      <label class="block text-sm font-medium text-gray-700">Nueva contraseña</label>
      <input
        type="password"
        formControlName="password"
        class="w-full px-4 py-2 mt-2 border rounded-md"
      />
      <p *ngIf="form.get('password')?.invalid && form.get('password')?.touched"
         class="text-red-500 text-sm mt-1">Campo requerido</p>

      <label class="block text-sm font-medium text-gray-700 mt-4">Confirmar contraseña</label>
      <input
        type="password"
        formControlName="confirmPassword"
        class="w-full px-4 py-2 mt-2 border rounded-md"
      />
      <p *ngIf="form.get('confirmPassword')?.touched && form.errors?.['passwordMismatch']"
         class="text-red-500 text-sm mt-1">Las contraseñas no coinciden</p>

      <button
        type="submit"
        class="w-full mt-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
      >
        Cambiar contraseña
      </button>
    </form>
  </div>
</div>

// 02_Frontend/innovatube/src/components/Security/Password/ResetPasswordComponent.jsx
import { useForm } from "react-hook-form";
import { useSearchParams, useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import { API_RESET_PASSWORD } from "../../../services/servicesApi";

const ResetPassword = () => {
  const { register, handleSubmit, formState: { errors }, watch } = useForm();
  const [params] = useSearchParams();
  const token = params.get("token");
  const navigate = useNavigate();

  const onSubmit = async (data) => {
    try {
      const res = await fetch(API_RESET_PASSWORD, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, NewPassword: data.password }),
      });

      const msg = await res.text();
      if (res.ok) {
        Swal.fire("Éxito", msg, "success").then(() => navigate("/"));
      } else {
        Swal.fire("Error", msg, "error");
      }
    } catch (err) {
      Swal.fire("Error", "No se pudo cambiar la contraseña", "error");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="w-full max-w-md bg-white p-6 rounded shadow-md">
        <h2 className="text-xl font-bold text-center mb-4">Restablecer contraseña</h2>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label className="block text-sm font-medium text-gray-700">Nueva contraseña</label>
          <input
            type="password"
            {...register("password", { required: "Campo requerido" })}
            className="w-full px-4 py-2 mt-2 border rounded-md"
          />
          {errors.password && <p className="text-red-500 text-sm mt-1">{errors.password.message}</p>}

          <label className="block text-sm font-medium text-gray-700 mt-4">Confirmar contraseña</label>
          <input
            type="password"
            {...register("confirmPassword", {
              required: "Confirmar contraseña es obligatorio",
              validate: value => value === watch("password") || "Las contraseñas no coinciden"
            })}
            className="w-full px-4 py-2 mt-2 border rounded-md"
          />
          {errors.confirmPassword && <p className="text-red-500 text-sm mt-1">{errors.confirmPassword.message}</p>}

          <button
            type="submit"
            className="w-full mt-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
          >
            Cambiar contraseña
          </button>
        </form>
      </div>
    </div>
  );
};

export default ResetPassword;
